version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret1!"
      ACCEPT_EULA: "Y"
    volumes:
      - .\data:/var/opt/mssql/data
    ports:
      - "1433:1433"
